//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGYCAHUB.Billing.BLL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LOGYCAHUB.Billing.BLL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERRV006.
        /// </summary>
        internal static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7701234900007.
        /// </summary>
        internal static string glnLOGYCA {
            get {
                return ResourceManager.GetString("glnLOGYCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERRV001.
        /// </summary>
        internal static string IdPais {
            get {
                return ResourceManager.GetString("IdPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 401.
        /// </summary>
        internal static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdPais.
        /// </summary>
        internal static string MethodCountry {
            get {
                return ResourceManager.GetString("MethodCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpirationDate.
        /// </summary>
        internal static string MethodExpirationDate {
            get {
                return ResourceManager.GetString("MethodExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OKExpirationDate.
        /// </summary>
        internal static string MethodOKExpirationDate {
            get {
                return ResourceManager.GetString("MethodOKExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OKMethodValidateBGM.
        /// </summary>
        internal static string MethodOKMethodValidateBGM {
            get {
                return ResourceManager.GetString("MethodOKMethodValidateBGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OKSupplierValidation.
        /// </summary>
        internal static string MethodOKSupplierValidation {
            get {
                return ResourceManager.GetString("MethodOKSupplierValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OKSupportForce.
        /// </summary>
        internal static string MethodOKSupportForce {
            get {
                return ResourceManager.GetString("MethodOKSupportForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OKValidatebalance.
        /// </summary>
        internal static string MethodOKValidatebalance {
            get {
                return ResourceManager.GetString("MethodOKValidatebalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OKValidateintegrity.
        /// </summary>
        internal static string MethodOKValidateintegrity {
            get {
                return ResourceManager.GetString("MethodOKValidateintegrity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierValidation.
        /// </summary>
        internal static string MethodSupplierValidation {
            get {
                return ResourceManager.GetString("MethodSupplierValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupportForce.
        /// </summary>
        internal static string MethodSupportForce {
            get {
                return ResourceManager.GetString("MethodSupportForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validatebalance.
        /// </summary>
        internal static string MethodValidatebalance {
            get {
                return ResourceManager.GetString("MethodValidatebalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidateBGM.
        /// </summary>
        internal static string MethodValidateBGM {
            get {
                return ResourceManager.GetString("MethodValidateBGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OKValidateCountry.
        /// </summary>
        internal static string MethodValidateCountry {
            get {
                return ResourceManager.GetString("MethodValidateCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidateGDSN.
        /// </summary>
        internal static string MethodValidateGDSN {
            get {
                return ResourceManager.GetString("MethodValidateGDSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validateintegrityglncomer.
        /// </summary>
        internal static string MethodValidateintegrityglncomer {
            get {
                return ResourceManager.GetString("MethodValidateintegrityglncomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validateintegrityglnprov.
        /// </summary>
        internal static string MethofValidateintegrityglnprov {
            get {
                return ResourceManager.GetString("MethofValidateintegrityglnprov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK006.
        /// </summary>
        internal static string OKExpirationDate {
            get {
                return ResourceManager.GetString("OKExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK007.
        /// </summary>
        internal static string OKMethodValidateBGM {
            get {
                return ResourceManager.GetString("OKMethodValidateBGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK008.
        /// </summary>
        internal static string OKSupplierValidation {
            get {
                return ResourceManager.GetString("OKSupplierValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK009.
        /// </summary>
        internal static string OKSupportForce {
            get {
                return ResourceManager.GetString("OKSupportForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK005.
        /// </summary>
        internal static string OKValidatebalance {
            get {
                return ResourceManager.GetString("OKValidatebalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK002.
        /// </summary>
        internal static string OKValidateCountry {
            get {
                return ResourceManager.GetString("OKValidateCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK001.
        /// </summary>
        internal static string OKValidateintegrity {
            get {
                return ResourceManager.GetString("OKValidateintegrity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;^[0-9]{4}$&quot;.
        /// </summary>
        internal static string regexBGMkey {
            get {
                return ResourceManager.GetString("regexBGMkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERRV008.
        /// </summary>
        internal static string SupplierValidation {
            get {
                return ResourceManager.GetString("SupplierValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERRV009.
        /// </summary>
        internal static string SupportForce {
            get {
                return ResourceManager.GetString("SupportForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 900.
        /// </summary>
        internal static string TokenAuthenticacion {
            get {
                return ResourceManager.GetString("TokenAuthenticacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERRV005.
        /// </summary>
        internal static string Validatebalance {
            get {
                return ResourceManager.GetString("Validatebalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERRV007.
        /// </summary>
        internal static string ValidateBGM {
            get {
                return ResourceManager.GetString("ValidateBGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERRV002.
        /// </summary>
        internal static string ValidateGDSN {
            get {
                return ResourceManager.GetString("ValidateGDSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERRV003.
        /// </summary>
        internal static string Validateintegrityglncomer {
            get {
                return ResourceManager.GetString("Validateintegrityglncomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERRV004.
        /// </summary>
        internal static string Validateintegrityglnprov {
            get {
                return ResourceManager.GetString("Validateintegrityglnprov", resourceCulture);
            }
        }
    }
}
