//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGYCAHUB.Billing.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICATS_X_EMPRESA
    {
        public string EAN_EMPRESA_GLN { get; set; }
        public int ID_EMPRESA { get; set; }
        public string ID_PAIS { get; set; }
        public int NUM_PRICATS_COMPRADOS { get; set; }
        public int NUM_PRICATS_PROCESADOS { get; set; }
        public Nullable<System.DateTime> FECHA_EXPIRACION { get; set; }
        public Nullable<bool> DESCONTAR_PRICAT { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZACION { get; set; }
        public Nullable<System.DateTime> FECHA_VENCIMIENTO_ORDEN { get; set; }
        public Nullable<int> ID_ORDEN_COMPRA { get; set; }
    }
}
