//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGYCAHUB.Billing.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOKENS
    {
        public int ID_TOKEN { get; set; }
        public int ID_USER { get; set; }
        public string AUTH_TOKEN { get; set; }
        public System.DateTime EMISION { get; set; }
        public System.DateTime EXPIRACION { get; set; }
    
        public virtual USER_API USER_API { get; set; }
    }
}
